// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "nmgapi": Application Contexts
//
// Command:
// $ goagen
// --design=github.com/btoll/rest-go/design
// --out=$(GOPATH)/src/github.com/btoll/rest-go
// --version=v1.3.0

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// ListEnumContext provides the Enum list action context.
type ListEnumContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewListEnumContext parses the incoming request URL and body, performs validations and creates the
// context used by the Enum controller list action.
func NewListEnumContext(ctx context.Context, r *http.Request, service *goa.Service) (*ListEnumContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ListEnumContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ListEnumContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// CreateEventContext provides the Event create action context.
type CreateEventContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Payload *EventPayload
}

// NewCreateEventContext parses the incoming request URL and body, performs validations and creates the
// context used by the Event controller create action.
func NewCreateEventContext(ctx context.Context, r *http.Request, service *goa.Service) (*CreateEventContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := CreateEventContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OKTiny sends a HTTP response with status code 200.
func (ctx *CreateEventContext) OKTiny(r *EventMediaTiny) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// DeleteEventContext provides the Event delete action context.
type DeleteEventContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID string
}

// NewDeleteEventContext parses the incoming request URL and body, performs validations and creates the
// context used by the Event controller delete action.
func NewDeleteEventContext(ctx context.Context, r *http.Request, service *goa.Service) (*DeleteEventContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := DeleteEventContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *DeleteEventContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *DeleteEventContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}

// ListEventContext provides the Event list action context.
type ListEventContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewListEventContext parses the incoming request URL and body, performs validations and creates the
// context used by the Event controller list action.
func NewListEventContext(ctx context.Context, r *http.Request, service *goa.Service) (*ListEventContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ListEventContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ListEventContext) OK(r EventMediaCollection) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/nmgapi.evententity; type=collection")
	if r == nil {
		r = EventMediaCollection{}
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKTiny sends a HTTP response with status code 200.
func (ctx *ListEventContext) OKTiny(r EventMediaTinyCollection) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/nmgapi.evententity; type=collection")
	if r == nil {
		r = EventMediaTinyCollection{}
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// ShowEventContext provides the Event show action context.
type ShowEventContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID string
}

// NewShowEventContext parses the incoming request URL and body, performs validations and creates the
// context used by the Event controller show action.
func NewShowEventContext(ctx context.Context, r *http.Request, service *goa.Service) (*ShowEventContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ShowEventContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ShowEventContext) OK(r *EventMedia) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKTiny sends a HTTP response with status code 200.
func (ctx *ShowEventContext) OKTiny(r *EventMediaTiny) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// UpdateEventContext provides the Event update action context.
type UpdateEventContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID      string
	Payload *EventPayload
}

// NewUpdateEventContext parses the incoming request URL and body, performs validations and creates the
// context used by the Event controller update action.
func NewUpdateEventContext(ctx context.Context, r *http.Request, service *goa.Service) (*UpdateEventContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := UpdateEventContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *UpdateEventContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *UpdateEventContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}

// CreateGameContext provides the Game create action context.
type CreateGameContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Payload *GamePayload
}

// NewCreateGameContext parses the incoming request URL and body, performs validations and creates the
// context used by the Game controller create action.
func NewCreateGameContext(ctx context.Context, r *http.Request, service *goa.Service) (*CreateGameContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := CreateGameContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OKTiny sends a HTTP response with status code 200.
func (ctx *CreateGameContext) OKTiny(r *GameMediaTiny) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// DeleteGameContext provides the Game delete action context.
type DeleteGameContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID string
}

// NewDeleteGameContext parses the incoming request URL and body, performs validations and creates the
// context used by the Game controller delete action.
func NewDeleteGameContext(ctx context.Context, r *http.Request, service *goa.Service) (*DeleteGameContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := DeleteGameContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *DeleteGameContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *DeleteGameContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}

// ListGameContext provides the Game list action context.
type ListGameContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewListGameContext parses the incoming request URL and body, performs validations and creates the
// context used by the Game controller list action.
func NewListGameContext(ctx context.Context, r *http.Request, service *goa.Service) (*ListGameContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ListGameContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ListGameContext) OK(r GameMediaCollection) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/nmgapi.gameentity; type=collection")
	if r == nil {
		r = GameMediaCollection{}
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKTiny sends a HTTP response with status code 200.
func (ctx *ListGameContext) OKTiny(r GameMediaTinyCollection) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/nmgapi.gameentity; type=collection")
	if r == nil {
		r = GameMediaTinyCollection{}
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// ShowGameContext provides the Game show action context.
type ShowGameContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID string
}

// NewShowGameContext parses the incoming request URL and body, performs validations and creates the
// context used by the Game controller show action.
func NewShowGameContext(ctx context.Context, r *http.Request, service *goa.Service) (*ShowGameContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ShowGameContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ShowGameContext) OK(r *GameMedia) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKTiny sends a HTTP response with status code 200.
func (ctx *ShowGameContext) OKTiny(r *GameMediaTiny) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// UpdateGameContext provides the Game update action context.
type UpdateGameContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID      string
	Payload *GamePayload
}

// NewUpdateGameContext parses the incoming request URL and body, performs validations and creates the
// context used by the Game controller update action.
func NewUpdateGameContext(ctx context.Context, r *http.Request, service *goa.Service) (*UpdateGameContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := UpdateGameContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *UpdateGameContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *UpdateGameContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}

// UploadImageContext provides the Image upload action context.
type UploadImageContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Entity string
	ID     string
}

// NewUploadImageContext parses the incoming request URL and body, performs validations and creates the
// context used by the Image controller upload action.
func NewUploadImageContext(ctx context.Context, r *http.Request, service *goa.Service) (*UploadImageContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := UploadImageContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramEntity := req.Params["entity"]
	if len(paramEntity) > 0 {
		rawEntity := paramEntity[0]
		rctx.Entity = rawEntity
	}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *UploadImageContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// CreateSportContext provides the Sport create action context.
type CreateSportContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Payload *SportPayload
}

// NewCreateSportContext parses the incoming request URL and body, performs validations and creates the
// context used by the Sport controller create action.
func NewCreateSportContext(ctx context.Context, r *http.Request, service *goa.Service) (*CreateSportContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := CreateSportContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OKTiny sends a HTTP response with status code 200.
func (ctx *CreateSportContext) OKTiny(r *SportMediaTiny) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// DeleteSportContext provides the Sport delete action context.
type DeleteSportContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID string
}

// NewDeleteSportContext parses the incoming request URL and body, performs validations and creates the
// context used by the Sport controller delete action.
func NewDeleteSportContext(ctx context.Context, r *http.Request, service *goa.Service) (*DeleteSportContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := DeleteSportContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *DeleteSportContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *DeleteSportContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}

// ListSportContext provides the Sport list action context.
type ListSportContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewListSportContext parses the incoming request URL and body, performs validations and creates the
// context used by the Sport controller list action.
func NewListSportContext(ctx context.Context, r *http.Request, service *goa.Service) (*ListSportContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ListSportContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ListSportContext) OK(r SportMediaCollection) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/nmgapi.sportentity; type=collection")
	if r == nil {
		r = SportMediaCollection{}
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKTiny sends a HTTP response with status code 200.
func (ctx *ListSportContext) OKTiny(r SportMediaTinyCollection) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/nmgapi.sportentity; type=collection")
	if r == nil {
		r = SportMediaTinyCollection{}
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// ShowSportContext provides the Sport show action context.
type ShowSportContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID string
}

// NewShowSportContext parses the incoming request URL and body, performs validations and creates the
// context used by the Sport controller show action.
func NewShowSportContext(ctx context.Context, r *http.Request, service *goa.Service) (*ShowSportContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ShowSportContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ShowSportContext) OK(r *SportMedia) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKTiny sends a HTTP response with status code 200.
func (ctx *ShowSportContext) OKTiny(r *SportMediaTiny) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// UpdateSportContext provides the Sport update action context.
type UpdateSportContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID      string
	Payload *SportPayload
}

// NewUpdateSportContext parses the incoming request URL and body, performs validations and creates the
// context used by the Sport controller update action.
func NewUpdateSportContext(ctx context.Context, r *http.Request, service *goa.Service) (*UpdateSportContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := UpdateSportContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *UpdateSportContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *UpdateSportContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}

// CreateTeamContext provides the Team create action context.
type CreateTeamContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Payload *TeamPayload
}

// NewCreateTeamContext parses the incoming request URL and body, performs validations and creates the
// context used by the Team controller create action.
func NewCreateTeamContext(ctx context.Context, r *http.Request, service *goa.Service) (*CreateTeamContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := CreateTeamContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OKTiny sends a HTTP response with status code 200.
func (ctx *CreateTeamContext) OKTiny(r *TeamMediaTiny) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// DeleteTeamContext provides the Team delete action context.
type DeleteTeamContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID string
}

// NewDeleteTeamContext parses the incoming request URL and body, performs validations and creates the
// context used by the Team controller delete action.
func NewDeleteTeamContext(ctx context.Context, r *http.Request, service *goa.Service) (*DeleteTeamContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := DeleteTeamContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *DeleteTeamContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *DeleteTeamContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}

// ListTeamContext provides the Team list action context.
type ListTeamContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewListTeamContext parses the incoming request URL and body, performs validations and creates the
// context used by the Team controller list action.
func NewListTeamContext(ctx context.Context, r *http.Request, service *goa.Service) (*ListTeamContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ListTeamContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ListTeamContext) OK(r TeamMediaCollection) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/nmgapi.teamentity; type=collection")
	if r == nil {
		r = TeamMediaCollection{}
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKTiny sends a HTTP response with status code 200.
func (ctx *ListTeamContext) OKTiny(r TeamMediaTinyCollection) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/nmgapi.teamentity; type=collection")
	if r == nil {
		r = TeamMediaTinyCollection{}
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// ShowTeamContext provides the Team show action context.
type ShowTeamContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID string
}

// NewShowTeamContext parses the incoming request URL and body, performs validations and creates the
// context used by the Team controller show action.
func NewShowTeamContext(ctx context.Context, r *http.Request, service *goa.Service) (*ShowTeamContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ShowTeamContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ShowTeamContext) OK(r *TeamMedia) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKTiny sends a HTTP response with status code 200.
func (ctx *ShowTeamContext) OKTiny(r *TeamMediaTiny) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// UpdateTeamContext provides the Team update action context.
type UpdateTeamContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID      string
	Payload *TeamPayload
}

// NewUpdateTeamContext parses the incoming request URL and body, performs validations and creates the
// context used by the Team controller update action.
func NewUpdateTeamContext(ctx context.Context, r *http.Request, service *goa.Service) (*UpdateTeamContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := UpdateTeamContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *UpdateTeamContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *UpdateTeamContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}

// CreateTeamOpeningConfigContext provides the TeamOpeningConfig create action context.
type CreateTeamOpeningConfigContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	Payload *TeamOpeningConfigPayload
}

// NewCreateTeamOpeningConfigContext parses the incoming request URL and body, performs validations and creates the
// context used by the TeamOpeningConfig controller create action.
func NewCreateTeamOpeningConfigContext(ctx context.Context, r *http.Request, service *goa.Service) (*CreateTeamOpeningConfigContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := CreateTeamOpeningConfigContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OKTiny sends a HTTP response with status code 200.
func (ctx *CreateTeamOpeningConfigContext) OKTiny(r *TeamOpeningConfigMediaTiny) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// DeleteTeamOpeningConfigContext provides the TeamOpeningConfig delete action context.
type DeleteTeamOpeningConfigContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID string
}

// NewDeleteTeamOpeningConfigContext parses the incoming request URL and body, performs validations and creates the
// context used by the TeamOpeningConfig controller delete action.
func NewDeleteTeamOpeningConfigContext(ctx context.Context, r *http.Request, service *goa.Service) (*DeleteTeamOpeningConfigContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := DeleteTeamOpeningConfigContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *DeleteTeamOpeningConfigContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *DeleteTeamOpeningConfigContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}

// ListTeamOpeningConfigContext provides the TeamOpeningConfig list action context.
type ListTeamOpeningConfigContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewListTeamOpeningConfigContext parses the incoming request URL and body, performs validations and creates the
// context used by the TeamOpeningConfig controller list action.
func NewListTeamOpeningConfigContext(ctx context.Context, r *http.Request, service *goa.Service) (*ListTeamOpeningConfigContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ListTeamOpeningConfigContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ListTeamOpeningConfigContext) OK(r TeamOpeningConfigMediaCollection) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/nmgapi.teamopeningconfigentity; type=collection")
	if r == nil {
		r = TeamOpeningConfigMediaCollection{}
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKTiny sends a HTTP response with status code 200.
func (ctx *ListTeamOpeningConfigContext) OKTiny(r TeamOpeningConfigMediaTinyCollection) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/nmgapi.teamopeningconfigentity; type=collection")
	if r == nil {
		r = TeamOpeningConfigMediaTinyCollection{}
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// ShowTeamOpeningConfigContext provides the TeamOpeningConfig show action context.
type ShowTeamOpeningConfigContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID string
}

// NewShowTeamOpeningConfigContext parses the incoming request URL and body, performs validations and creates the
// context used by the TeamOpeningConfig controller show action.
func NewShowTeamOpeningConfigContext(ctx context.Context, r *http.Request, service *goa.Service) (*ShowTeamOpeningConfigContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := ShowTeamOpeningConfigContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *ShowTeamOpeningConfigContext) OK(r *TeamOpeningConfigMedia) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// OKTiny sends a HTTP response with status code 200.
func (ctx *ShowTeamOpeningConfigContext) OKTiny(r *TeamOpeningConfigMediaTiny) error {
	ctx.ResponseData.Header().Set("Content-Type", "application/json")
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// UpdateTeamOpeningConfigContext provides the TeamOpeningConfig update action context.
type UpdateTeamOpeningConfigContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
	ID      string
	Payload *TeamOpeningConfigPayload
}

// NewUpdateTeamOpeningConfigContext parses the incoming request URL and body, performs validations and creates the
// context used by the TeamOpeningConfig controller update action.
func NewUpdateTeamOpeningConfigContext(ctx context.Context, r *http.Request, service *goa.Service) (*UpdateTeamOpeningConfigContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := UpdateTeamOpeningConfigContext{Context: ctx, ResponseData: resp, RequestData: req}
	paramID := req.Params["id"]
	if len(paramID) > 0 {
		rawID := paramID[0]
		rctx.ID = rawID
	}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *UpdateTeamOpeningConfigContext) OK(resp []byte) error {
	ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}

// NoContent sends a HTTP response with status code 204.
func (ctx *UpdateTeamOpeningConfigContext) NoContent() error {
	ctx.ResponseData.WriteHeader(204)
	return nil
}
